# Generated by Django 4.0.4 on 2022-04-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0008_rename_sube_customuser_sube_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='amount',
            new_name='balance',
        ),
    ]
